# =============================================================================
# TIMEFLIES BATCH CORRECTION CONFIGURATION
# =============================================================================
# Configuration for scVI batch correction and PyTorch environment.
# Users can customize these settings before running batch correction.

# Project-specific overrides for batch correction
# Add any new project here with hierarchical settings following the main config structure
project_overrides:
  fruitfly_aging:
    batch_correction:
      enabled: true                        # Enable/disable batch correction for this project
      preprocessing:
        batch_column: "dataset"
        label_column: "afca_annotation_broad"
      evaluation:
        plot_columns: ["dataset", "sex", "age", "genotype"]
  fruitfly_alzheimers:
    batch_correction:
      enabled: true                        # Enable/disable batch correction for this project
      preprocessing:
        batch_column: "dataset"
        label_column: "afca_annotation_broad"
      evaluation:
        plot_columns: ["dataset", "sex", "age", "genotype"]
  # Add new projects here (can override any part of the config):
  # your_new_project:
  #   batch_correction:
  #     enabled: false                     # Disable batch correction completely
  # example_project_with_custom_settings:
  #   batch_correction:
  #     enabled: true                      # Enable with custom settings
  #     model:
  #       n_latent: 30
  #     preprocessing:
  #       batch_column: "sample_id"
  #       label_column: "cell_type"
  #       library_size: 1e5
  #     evaluation:
  #       plot_columns: ["sample_id", "condition", "timepoint"]
  #       run_metrics: true

# Default scVI Model Configuration
batch_correction:
  enabled: true                     # Default: batch correction enabled (can be overridden per project)

  model:
    n_latent: 25              # Latent space dimensions
    n_hidden: 256             # Hidden layer size
    n_layers: 2               # Number of layers
    dropout_rate: 0.15        # Dropout rate

  # Training parameters
  training:
    max_epochs: null          # null = early stopping
    weight_decay: 1e-4        # Weight decay for regularization
    plan_kwargs:
      weight_decay: 1e-4

  # Data processing (defaults - overridden by project_overrides)
  preprocessing:
    batch_column: "dataset"              # Column containing batch information
    label_column: "afca_annotation_broad" # Cell type annotation column
    library_size: 1e4                    # Target library size for normalization
    sampling:
      samples: null        # null = use all data, or specify number (e.g., 10000)
      variables: null      # null = use all genes, or specify number (e.g., 2000)

  # Output settings
  output:
    scvi_latent_key: "X_scVI"            # Key for latent representations
    scvi_normalized_key: "scvi_normalized" # Key for normalized data
    save_intermediate: true               # Save intermediate results

  # Evaluation settings
  evaluation:
    run_metrics: false        # Set to true to automatically run evaluation metrics
    run_visualization: false # Set to true to automatically generate UMAPs
    metrics_output_dir: "outputs/{project}/results/batch_correction"
    umap_output_dir: "outputs/{project}/results/batch_correction/umaps"
    plot_columns: ["dataset", "sex", "age", "genotype"]  # Default columns (overridden by project_overrides)

# PyTorch Environment Configuration
pytorch:
  float32_matmul_precision: "medium"    # Options: "medium", "high", "highest"
  dl_num_workers: -1                    # -1 = cpu_count() - 1
  dl_pin_memory: true                   # Pin memory for faster GPU transfer
  seed: 42                              # Random seed for reproducibility
