# Default configuration for TimeFlies project

# General settings
general:
  project_name: "TimeFlies"
  version: "0.2.0"
  random_state: 42

# Device configuration
device:
  processor: "GPU"  # Options: "GPU", "CPU", "M" (Apple Silicon)
  gpu_memory_growth: true

# Data parameters
data:
  # General settings
  tissue: "head"  # Options: "head", "body", "all"
  model_type: "CNN"  # Options: "CNN", "MLP", "logistic", "xgboost", "random_forest"
  encoding_variable: "age"  # Options: "age", "sex", "tissue", "dataset"
  cell_type: "all"  # Options: "all", specific cell types
  sex_type: "all"  # Options: "all", "male", "female"
  
  # Batch correction
  batch_correction:
    enabled: true
    
  # Filtering
  filtering:
    include_mixed_sex: false
    
  # Sampling
  sampling:
    num_samples: null  # null for all samples
    num_variables: null  # null for all variables
    
  # Train-test split
  train_test_split:
    # Split method - IMPORTANT:
    # - "random": Standard random split using test_split ratio (ignores train/test settings below)
    # - "sex": Train on one sex, test on another (uses train.sex and test.sex)
    # - "tissue": Train on one tissue, test on another (uses train.tissue and test.tissue)
    method: "random"  # Options: "random", "sex", "tissue"
    test_split: 0.2   # Used only when method="random"
    random_state: 42
    
    # Settings below are ONLY used when method="sex" or method="tissue"
    # They are IGNORED when method="random"
    train:
      sex: "male"      # Used only when method="sex"
      tissue: "head"   # Used only when method="tissue"
    test:
      sex: "female"    # Used only when method="sex"
      tissue: "body"   # Used only when method="tissue"
      size: 0.3        # Optional: limit test set size for sex/tissue splits

# Gene preprocessing
gene_preprocessing:
  # Gene filtering
  gene_filtering:
    remove_sex_genes: false
    remove_autosomal_genes: false
    only_keep_lnc_genes: false
    remove_lnc_genes: false
    remove_unaccounted_genes: false
    select_batch_genes: false
    highly_variable_genes: false
    
  # Gene balancing
  gene_balancing:
    balance_genes: false
    balance_lnc_genes: false
    
  # Gene shuffling
  gene_shuffle:
    shuffle_genes: false
    shuffle_random_state: 42

# Data processing
data_processing:
  # Preprocessing
  preprocessing:
    required: true
    save_data: true
    
  # Model management
  model_management:
    load_model: false      # Load existing model instead of training
    model_path: null       # Path to existing model (if load_model=true)
    
  # Normalization
  normalization:
    enabled: false

# Model parameters
model:
  # Training parameters
  training:
    epochs: 100
    batch_size: 32
    validation_split: 0.2
    early_stopping_patience: 10
    learning_rate: 0.001
    
  # Model architecture (CNN specific)
  cnn:
    filters: [32]              # Only one convolutional layer
    kernel_sizes: [3]          # Corresponding kernel size
    strides: [1]
    paddings: ["same"] 
    pool_sizes: [2]
    pool_strides: [2]
    
    dense_units: [128]         # Only one fully connected layer before output
    dropout_rate: 0.5
    activation: "relu"
    
  # Model architecture (MLP specific)
  mlp:
    hidden_layers: [512, 256, 128]
    activation: "relu"
    dropout_rate: 0.2
    
  # Model architecture (XGBoost specific)
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    eval_metric: "mlogloss"  # Will auto-adjust based on problem type
    
  # Model architecture (Random Forest specific)
  random_forest:
    n_estimators: 100
    max_depth: null  # No limit
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    
  # Model architecture (Logistic Regression specific)
  logistic:
    max_iter: 1000
    C: 1.0  # Regularization strength
    penalty: "l2"  # Regularization type
    solver: "lbfgs"

# Feature importance and visualizations
feature_importance:
  run_interpreter: true     # Enable/disable SHAP interpretation
  run_visualization: true   # Enable/disable visualization generation
  load_SHAP: false          # Load existing SHAP values instead of computing
  reference_size: 100
  
# File locations
file_locations:
  training_file: "fly_train.h5ad"
  evaluation_file: "fly_eval.h5ad"
  original_file: "fly_original.h5ad"
  batch_corrected_files:
    train: "fly_train_batch.h5ad"
    eval: "fly_eval_batch.h5ad"

# Logging
logging:
  level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  format: "detailed"  # Options: "simple", "detailed", "json"
  log_to_file: false
  log_directory: "logs"
  log_filename: "timeflies.log"