# =============================================================================
# TIMEFLIES DEFAULT CONFIGURATION
# =============================================================================
# Shared settings across all projects. Project-specific overrides go in 
# project folders (fruitfly_aging/, fruitfly_alzheimers/)

# =============================================================================
# PROJECT SETTINGS
# =============================================================================
project: fruitfly_aging  # <-- CHANGE THIS TO SWITCH PROJECTS

general:
  version: "0.2.0"
  random_state: 42

# =============================================================================
# HARDWARE CONFIGURATION  
# =============================================================================
hardware:
  processor: "GPU"  # Options: "GPU", "CPU", "M" (Apple Silicon)
  memory_growth: true

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  # Core data settings
  model: "CNN"  # Options: "CNN", "MLP", "logistic", "xgboost", "random_forest"
  tissue: "head"  # Options: "head", "body", "all"
  species: "drosophila"
  cell_type: "all"
  sex: "all"  # Options: "all", "male", "female"
  
  # Data processing options
  batch_correction:
    enabled: false  # Set to true to use batch-corrected data
    
  filtering:
    include_mixed_sex: false
    
  sampling:
    samples: 1000  # null for all samples, or specify number
    variables: null  # null for all genes, or specify number
    
  # Train-test splitting strategies
  split:
    # Method options:
    # - "random": Standard random split using test_ratio (ignores other settings)
    # - "sex": Train on one sex, test on another (uses sex_split settings)  
    # - "tissue": Train on one tissue, test on another (uses tissue_split settings)
    method: "random"  # Options: "random", "sex", "tissue"
    test_ratio: 0.1   # Used only when method="random"
    
    # Sex-based splitting (used only when method="sex")
    sex:
      train: "male"    # Train on males
      test: "female"   # Test on females
      test_ratio: 0.3  # Subsample test set to avoid huge test sizes
      
    # Tissue-based splitting (used only when method="tissue")
    tissue:
      train: "head"    # Train on head tissue
      test: "body"     # Test on body tissue
      test_ratio: 0.3  # Subsample test set to avoid huge test sizes

# =============================================================================
# FILE PATHS (AUTO-GENERATED FROM TEMPLATES)
# =============================================================================
# Uses template variables: {project}, {tissue}, {species}
paths:
  # Input/output data files
  data:
    train: "data/{project}/{tissue}/{species}_{tissue}_{project}_train.h5ad"
    eval: "data/{project}/{tissue}/{species}_{tissue}_{project}_eval.h5ad"
    original: "data/{project}/{tissue}/{species}_{tissue}_{project}_original.h5ad"
    
  # Batch-corrected versions
  batch_data:
    train: "data/{project}/{tissue}/{species}_{tissue}_{project}_train_batch.h5ad"
    eval: "data/{project}/{tissue}/{species}_{tissue}_{project}_eval_batch.h5ad"

# =============================================================================
# MODEL CONFIGURATION
# =============================================================================
model:
  # Shared training parameters (architectures defined in project configs)
  training:
    epochs: 100
    batch_size: 32
    validation_split: 0.2
    early_stopping_patience: 8
    learning_rate: 0.001

# =============================================================================
# PREPROCESSING CONFIGURATION
# =============================================================================
preprocessing:
  # Gene filtering options
  genes:
    remove_sex_genes: false          # Remove sex-linked genes
    remove_autosomal_genes: false    # Remove autosomal genes
    only_keep_lnc_genes: false       # Keep only long non-coding genes
    remove_lnc_genes: false          # Remove long non-coding genes
    remove_unaccounted_genes: false  # Remove unaccounted genes
    highly_variable_genes: false     # Filter for highly variable genes
    
  # Gene balancing
  balancing:
    balance_genes: false
    balance_lnc_genes: false
    
  # Gene shuffling
  shuffling:
    shuffle_genes: false

# Gene preprocessing configuration (legacy structure expected by code)
gene_preprocessing:
  gene_filtering:
    remove_sex_genes: false          # Remove sex-linked genes
    remove_autosomal_genes: false    # Remove autosomal genes
    only_keep_lnc_genes: false       # Keep only long non-coding genes
    remove_lnc_genes: false          # Remove long non-coding genes
    remove_unaccounted_genes: false  # Remove unaccounted genes
    highly_variable_genes: false     # Filter for highly variable genes
    select_batch_genes: false        # Select genes based on batch
    
  gene_balancing:
    balance_genes: false
    balance_lnc_genes: false
    
  gene_shuffle:
    shuffle_genes: false
    shuffle_random_state: 42

# =============================================================================
# ANALYSIS CONFIGURATION  
# =============================================================================
analysis:
  # Data normalization
  normalization:
    enabled: false
    
  # Exploratory data analysis
  eda:
    enabled: false

# Data processing configuration (legacy structure expected by code)
data_processing:
  # Data normalization
  normalization:
    enabled: false
    
  # Exploratory data analysis
  exploratory_data_analysis:
    enabled: false
    
# Feature importance analysis
interpretation:
  shap:
    enabled: false           # Enable/disable SHAP interpretation (includes visualizations)
    load_existing: false     # Load existing SHAP values instead of computing
    reference_size: 100      # Reference size for SHAP analysis

# Visualizations
visualizations:
  enabled: true             # Enable general visualizations (training plots, confusion matrix, ROC curves, etc.)

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level: "INFO"              # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  format: "detailed"         # Options: "simple", "detailed", "json"
  to_file: false             # Save logs to file
  directory: "logs"          # Log directory
  filename: "timeflies.log"  # Log filename