# =============================================================================
# TIMEFLIES SETUP CONFIGURATION
# =============================================================================
# Configuration for data splitting and sampling during initial setup.
# Users can customize these settings before running 'timeflies setup'.
#
# RE-RUNNING SETUP:
# - Setup is safe to run multiple times (e.g., after batch correction)
# - Existing splits are preserved unless split parameters change
# - Batch-corrected files are verified for consistency (same cells/genes/order)
# - Only missing files are created, existing files are verified
# - Use --force-split to recreate splits with new parameters:
#   timeflies setup --force-split    # Recreates train/eval splits, verifies batch files

# Data splitting configuration
train_test_split:
  split_size: 5000          # Number of cells in evaluation set
  stratify_by: ["age"]      # Columns to stratify by (can be single string or list)
  fallback_ratio: 0.2       # Fallback test ratio if split_size too large
  random_state: 42          # Random seed for reproducible splits

# Sampling configuration
sampling:
  num_samples: null         # null = use all samples, or specify number
  num_variables: null       # null = use all genes, or specify number

# Directory structure
directories:
  create_batch_corrected: true    # Create batch-corrected output directories
  create_project_dirs: true       # Create project-specific directories

# Project-specific overrides (optional)
# Override settings for specific data folder names found in data/
# The project name must match your data/ folder structure: data/[project_name]/[tissue]/
project_overrides:
  # Example: Different stratification for different datasets
  # fruitfly_alzheimers:          # Matches data/fruitfly_alzheimers/ folder
  #   stratify_by: ["age", "genotype"]
  #   split_size: 3000
  # my_custom_project:            # Would match data/my_custom_project/ folder
  #   stratify_by: ["timepoint", "condition"]
  #   fallback_ratio: 0.15
